name: Product Analytics
permissions:
  contents: read

on:
  schedule:
    - cron: '0 9 * * MON'  # Every Monday at 9 AM
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Product Insights
      run: |
        python scripts/product_insights_cli.py weekly --since 1w > weekly_report.txt
        python scripts/product_insights_cli.py executive --since 1w > executive_summary.json

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: weekly-product-report
        path: |
          weekly_report.txt
          executive_summary.json

    - name: Send Slack Notification
      if: env.SLACK_WEBHOOK_URL != ''
      run: |
        python scripts/notification_system.py process executive_summary.json
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
